export enum AppTarget {
    ADMIN_APP_LOADER = 'ADMIN_APP_LOADER',
    ADMIN_APPOINTMENT_DETAILS = 'ADMIN_APPOINTMENT_DETAILS',
    EXPERIENCE_BEFORE_CART = 'EXPERIENCE_BEFORE_CART',
    EXPERIENCE_BOOKING_FORM = 'EXPERIENCE_BOOKING_FORM',
    EXPERIENCE_BOOKING_SUCCESS = 'EXPERIENCE_BOOKING_SUCCESS',
    EXPERIENCE_RESCHEDULING_SUCCESS = 'EXPERIENCE_RESCHEDULING_SUCCESS'
}
