export enum AppTarget {
    ADMIN_APP_LOADER = 'ADMIN_APP_LOADER',
    ADMIN_APPOINTMENT_DETAILS = 'ADMIN_APPOINTMENT_DETAILS',
    EXPERIENCE_BEFORE_CART = 'EXPERIENCE_BEFORE_CART',
    EXPERIENCE_INSTANT_BOOKING_FORM = 'EXPERIENCE_INSTANT_BOOKING_FORM',
    EXPERIENCE_CONFIRMATION_PAGE = 'EXPERIENCE_CONFIRMATION_PAGE'
}
