name: PUBLISH

on:
  push:
    branches: [ master ]
    paths:
    - 'package.json'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-to-git:
    name: Publish to Git
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        registry-url: https://npm.pkg.github.com/
        scope: '@sesamiapp'
    - name: add token in .npmrc file
      run: |
        echo "@sesamiapp:registry=https://npm.pkg.github.com/" > ~/.npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
    - name: install dependencies
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_NPM_TOKEN }}
    - name: building the library
      run: npm run build
    - name: publish package
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}