name: Prerelease to npmjs.com
on:
  pull_request_review:
    types:
      - submitted
jobs:
  publish-to-npm:
    if: ${{ github.ref == 'refs/heads/master' || github.event.review.body == 'deploy' }}
    name: Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@sesamiapp'
          cache: 'pnpm'
      - name: install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Bump prerelease version
        run: |
          npm version prerelease --preid=beta --no-git-tag-version
      - name: building the library
        run: pnpm run build
      - name: publish package to npm
        run: pnpm publish --tag beta --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}