name: Publish to npmjs.com
on:
  release:
    types: [ released ]
jobs:
  publish-to-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@sesamiapp'
          cache: 'pnpm'
      - name: install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: building the library
        run: pnpm run build
      - name: publish package to npm
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}